### ISSUE TITLE
Issue on level 8 "soil"

### ISSUE THREAD

**Issue by Tx-Charlie** [halfsail/Chromatic#12]
Issue on level 8 "soil". Seems level 8 "soil" 's color data not exist in file `colors.js`. (O.O;

**Comment by ch3pjw** [comment]
Oh bummer, thanks for reporting this, I must have missed that in the big refactor of the code I did. Unfortunately I don't have the phone and development environment any more, but I'd be really happy to review any changes you'd want to make to fix this.

I think the broad approach would be to look back through the history to before my refactor (basically, before any of my commits) and see what the original data looked like, then copy it into the new `color.js` file.

**Comment by Tx-Charlie** [comment]
Cool xD

Em.. by the way, I'm try to rewrite your game `Chromatic` in Qt C++ (https://github.com/Texas-C/Chromatic-cute). 

It's really a nice game. I played `Chromatic` when I bought a Meizu MX4 with Ubuntu-touch edition in 2015 (But my mx4 broken now.. sad TuT). So I want to make it available for other enviroment. ( is it okay?... em.. is there any liscene issue? O.O)

Currently, original puzzles are works now (load original puzzle by `colors.json` and `puzzles.json` which from orignal `Chromatic` project). 

But still has some bugs (apologize for my poor coding skill TuT).

And... I'd like to add some features like "puzzle editor" for custome puzzle... 

Really thanks :D

**Comment by ch3pjw** [comment]
Oh, cool, that's great. The original project was by @halfsail, not me, but as far as I'm aware his intent was to keep it open so people could do exactly the kind of thing you're doing.

**Comment by Tx-Charlie** [comment]
Thanks :D

**Comment by Tx-Charlie** [comment]
Hi~ Happy new year !

I found a method to build & install this project :D. With this tool `Clickable`.( Document: http://clickable.bhdouglass.com/en/latest/index.html)

It's not that complicate to setup `clickable`.

I'm already tested on nexus4 with Ubuntu touch. I copied orignal files on Chromatic to `clickable` created empty qml project. Then call `clickable` to build & install.

build cmd:
```
# create a empty project with wizard, for example created a pure qml project named Chromatic-clickable-version
clickable create 

# copy orignal Chromatic's files to new ones:
cp ${YOUR_PATH}/Chromatic/* Chromatic-clickable-version/qml/

# build / install on device
cd Chromatic-clickable-version
clickable

# this commands just made Chromatic works on new build system. So need some other setup (like icon).
```


Finally, I found this issue is solved. And level "soil" became `level 9` now :D

**Comment by ch3pjw** [comment]
Nice - glad it worked. Happy New Year :tada: to you too. I'll take a look at `clickable`.
