### ISSUE TITLE
Add haptic feedback to buttons

### ISSUE THREAD

**Issue by krnekhelesh** [halfsail/Chromatic#6]
Many a times I wonder if I pressed a button or not since there is no visual or haptic feedback. You can easily add haptic feedback to a button by,

Haptics.play() to the onClicked{} signal of any button.

**Comment by halfsail** [comment]
This is a thing!? Why is this not in the documentation for the mouseArea? 
Well anyways haptic feedback has been added.

**Comment by krnekhelesh** [comment]
It is not there because MouseArea is a component developed by QT and is used to fire signals only. While the Haptics was developed by the Ubuntu SDK Developers. It is documented in the offline SDK docs that you can find in Qtcreator.

**Comment by halfsail** [comment]
Is there anyway to submit a bug to get it added?

**Comment by krnekhelesh** [comment]
It is not a bug really. Usually if you want something you need to add it yourself. In your case you used a Icon and added a mouse area to it which defines what needs to be done when you click it. And if you want haptic feedback, then you add that statement. Some people might not want haptic feedback for every clicked signal for instance.
