### ISSUE TITLE
Auto-indent code

### ISSUE THREAD

**Issue by krnekhelesh** [halfsail/Chromatic#7]
If you're using Qtcreator, you can autoindent code in a file by selecting all (Ctrl+a) and then pressing Ctrl+i. That will autoindent code for you and make the code more clearer to go through.

**Comment by halfsail** [comment]
This is amazing. :)

**Comment by ch3pjw** [comment]
I'm presuming this is ok with the latest code? I was editing in emacs, so the indentation might be a little different to the standard!
